### ISSUE TITLE
Multiple players not working

### ISSUE THREAD

**Issue by bosbode** [chintan9/plyr-react#836] opened 2022-05-20 12:46 UTC
When mapping through multiple items, all with their own player. Only one player loads the rest stay blank.

**Comment by realamirhe** [comment] 2022-05-20 14:09
Thanks for your report @bosbode,
Could you please reproduce the scenario in a code sandbox, so we can discuss it further in the frozen environment and update you with the changes?

**Comment by bosbode** [comment] 2022-05-25 09:17
Hi @realamirhe thanks for the reply. Here's the sandbox https://codesandbox.io/s/elated-faraday-3r194i
In the sandbox the players load the posters, but when you press play nothing happens. When loading a single video from the json file it works as expected.

**Comment by realamirhe** [comment] 2022-05-26 03:42
hey @bosbode, the problem seems to exist because of SSR issue.

The Plyr should interact with the dom, and the way it should be used is something like [this](https://chaseohlson.com/plyr-gatsby-youtube-vimeo)

We might make a helper wrapper for the SSR support to try to load the package only to the client.


Also, I made a NextJs version of your code sandbox in our example director ([example/nextjs](https://github.com/chintan9/plyr-react/blob/master/example/nextjs/pages/index.js))
and try to load it on the client-side via the next `dynamic` but it didn't behave as expected

There is also a react version of exact same things, which let you interact with all of the videos 
([example/react/video-list](https://github.com/chintan9/plyr-react/blob/master/example/react/src/video-list/video-list.tsx))

**Comment by bosbode** [comment] 2022-05-26 11:50
Hey @realamirhe, thanks for the looking into it. I've fixed by using the normal PLYR package. https://codesandbox.io/s/frosty-cache-6j67ms

**Comment by realamirhe** [comment] 2022-05-26 13:40
Nice to hear that
So I'm going to close the issue, feel free to open a new one if it remains.

**Closed by realamirhe** 2022-05-26 13:40 UTC
